### ISSUE TITLE
Verificare se funziona "nascondi report automatici"

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#10]

**Comment by nicomazz** [comment]
non mi risulta esista questa funzione

**Comment by marziaf** [comment]
On 15 Feb 2017 11:55 a.m., "Nicolò Mazzucato" <notifications@github.com>
wrote:

non mi risulta esista questa funzione

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nicomazz/Orari-Autobus-Actv/issues/10#issuecomment-279980054>,
or mute the thread

**Comment by nicomazz** [comment]
non ho capito cos'hai commentato
