### ISSUE TITLE
Crash ogni volta che si apre un punto vendita!

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#11]

**Comment by nicomazz** [comment]
in che senso? a me no

**Comment by marziaf** [comment]
Se clicco su un punto vendita crasha... cosa devo spiegare?

**Comment by nicomazz** [comment]
a me non crasha. Intendi quando premi il punto della lista o  dalla mappa?

**Comment by marziaf** [comment]
Lista

**Comment by nicomazz** [comment]
Si trattava di un problema con openGL. Ho tolto l'animazione quando si preme un punto vendita e ora funziona.
