### ISSUE TITLE
Negli orari i "colori delle fermate" sono sbagliati.

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#2]
![photo_2017-02-14_21-40-14](https://cloud.githubusercontent.com/assets/25252689/22948296/2f0e809a-f2fe-11e6-9d63-9bc128a3bb58.jpg)

**Comment by nicomazz** [comment]
In che senso?

**Comment by marziaf** [comment]
Ti ho mandato anche l'immagine.

**Comment by nicomazz** [comment]
era colpa dell'actv che mette nomi del tipo "via ciardi," " cipressina " " ". risolto
