### ISSUE TITLE
Scroll orari

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#3]
Dopo aver aperto un autobus, clicco sull'icona degli orari. Si aprono gli orari ma lo scroll non è anche obliquo, solo verticale ed orizzontale
![photo_2017-02-14_21-40-54](https://cloud.githubusercontent.com/assets/25252689/22948331/5376d158-f2fe-11e6-9efc-e54f5ffc07ab.jpg)

**Comment by nicomazz** [comment]
Giusto così, funziona come dovrebbe. Se avrò voglia metterò a posto in futuro

**Comment by nicomazz** [comment]
Risolto
