### ISSUE TITLE
avvio la navigazione. Spostare le bandierine non fa nulla

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#4]
O cambia il percorso o non si spostano. Non rilevante
![photo_2017-02-14_21-42-10](https://cloud.githubusercontent.com/assets/25252689/22948364/7cc63940-f2fe-11e6-9e3c-5ef9625f736b.jpg)

**Comment by nicomazz** [comment]
Risolto
