### ISSUE TITLE
Barra delay negli orari a volte è visibile

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#5]
![photo_2017-02-14_21-43-12](https://cloud.githubusercontent.com/assets/25252689/22948390/9a63c21a-f2fe-11e6-86eb-7a2132fe508b.jpg)

**Comment by nicomazz** [comment]
È visibile solo quando ci sono ritardi segnalati in quell'autobus. Funziona come dovrebbe
