### ISSUE TITLE
Cambio d'autobus con lo stesso autobus e percorsi a piedi di 0 metri

### ISSUE THREAD

**Issue by marziaf** [nicomazz/Orari-Autobus-Actv#6]
![photo_2017-02-14_21-34-14](https://cloud.githubusercontent.com/assets/25252689/22948037/5f7957e2-f2fd-11e6-8e98-4b2052698207.jpg)
![photo_2017-02-14_21-34-18](https://cloud.githubusercontent.com/assets/25252689/22948042/612a4dda-f2fd-11e6-858c-607a18d946a6.jpg)

**Comment by nicomazz** [comment]
mi servono fermate di partenza, di destinazione e orari delle navigazioni.
Per quanto riguarda la seconda immagine è perchè ci sono 2 fermate sovrapposte (colpa di actv)

**Comment by nicomazz** [comment]
Trovati. Non si tratta dello stesso autobus. Aprendo i dettagli si può vedere che uno parte da catene e l'altro da Marghera. Arrivano in quella fermata contemporaneamente. Non essendo la prima soluzione (ma la quarta) la cosa è giusta.
